In [2]:
ls

cars.csv             model_testing.ipynb


In [3]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
import pickle 
import numpy 

In [4]:
df = pd.read_csv('cars.csv')
target = df.mpg 
X = df[['cylinders', 'horsepower', 'weight']]

In [6]:
model = LinearRegression()
model.fit(X,target)
print(model.coef_)

[-1.11439132  0.09151962 -0.00850185]


In [7]:
cyl = 8
horse = 200
weight = 2000
model.predict([[cyl,horse,weight]])

array([39.10656063])

In [8]:
pickle.dump(model,open('linreg.p','wb'))

In [9]:
import pickle 
model = pickle.load(open('linreg.p','rb'))

cyl = 8
horse = 200
weight = 2000
model.predict([[cyl,horse,weight]])

array([39.10656063])